### ISSUE TITLE
mat1 and mat2 shapes

### ISSUE THREAD

**Issue by QUEST2179** [karma211225/KarmaLoop#1]
Just followed instruction for single_example but got the following error, could you please help?

python -u loop_generating.py --graph_file_dir ../example/single_example/graph --out_dir ../example/single_example/test_result --batch_size 64 --random_seed 2023 --multi_conformation --scoring --save_file 

########### Start modelling loop ###########
pdb_ids: 3
# load model
  0%|                                                                                             | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/antibody/KarmaLoop-main/utils/loop_generating.py", line 121, in <module>
    pos_pred, mdn_score = model.module.modelling_loop(data, scoring=args.scoring, recycle_num=3, dist_threhold=5)
  File "/home/antibody/KarmaLoop-main/architecture/Net_architecture.py", line 175, in modelling_loop
    pro_node_s, loop_node_s = self.encoding(data)
  File "/home/antibody/KarmaLoop-main/architecture/Net_architecture.py", line 78, in encoding
    proatom_node_s = self.loop_encoder(data['protein_atom'].node_s.to(torch.float32), data['protein_atom', 'pa2pa', 'protein_atom'].edge_s.to(torch.float32), data['protein_atom', 'pa2pa', 'protein_atom'].edge_index)
  File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/antibody/KarmaLoop-main/architecture/GraphTransformer_Block.py", line 428, in forward
    edge_feats = self.edge_encoder(edge_s)
  File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4984x22 and 20x128)

**Comment by Karobben** [comment]
> Just followed instruction for single_example but got the following error, could you please help?
> 
> python -u loop_generating.py --graph_file_dir ../example/single_example/graph --out_dir ../example/single_example/test_result --batch_size 64 --random_seed 2023 --multi_conformation --scoring --save_file
> 
> ########### Start modelling loop ########### pdb_ids: 3
> 
> # load model
> 0%| | 0/1 [00:01<?, ?it/s] Traceback (most recent call last): File "/home/antibody/KarmaLoop-main/utils/loop_generating.py", line 121, in pos_pred, mdn_score = model.module.modelling_loop(data, scoring=args.scoring, recycle_num=3, dist_threhold=5) File "/home/antibody/KarmaLoop-main/architecture/Net_architecture.py", line 175, in modelling_loop pro_node_s, loop_node_s = self.encoding(data) File "/home/antibody/KarmaLoop-main/architecture/Net_architecture.py", line 78, in encoding proatom_node_s = self.loop_encoder(data['protein_atom'].node_s.to(torch.float32), data['protein_atom', 'pa2pa', 'protein_atom'].edge_s.to(torch.float32), data['protein_atom', 'pa2pa', 'protein_atom'].edge_index) File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/antibody/KarmaLoop-main/architecture/GraphTransformer_Block.py", line 428, in forward edge_feats = self.edge_encoder(edge_s) File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward return F.linear(input, self.weight, self.bias) RuntimeError: mat1 and mat2 shapes cannot be multiplied (4984x22 and 20x128)

I think she updated the codes and solved the problem. But now, instead of edge features, it has a problem with node features. In the model, it has 89 features. But in the generated graphic,it has only 88

**Comment by Karobben** [comment]
I tried to pad the graphic into 89 and the results are terrible. It seems that they didn't check their GitHub frequently.

**Comment by karma211225** [comment]
I appreciate your effort in addressing this issue. I wanted to share that the problem occurs when using the following reproduction code. I’m wondering if there's any possibility that the Conda environment might be incorrectly configured. The `KarmaLoop` Conda environment can be downloaded from [this link](https://zenodo.org/records/8032172). Additionally, I would like to confirm whether the `reproduction.sh` script can be successfully executed in your device. Please let me know if you encounter any other problems or need further clarification.
```shell 
git clone https://github.com/karma211225/KarmaLoop.git
cd /root/KarmaLoop/utils 
python -u pre_processing.py --protein_file_dir /root/KarmaLoop/example/single_example/raw --pocket_file_dir /root/KarmaLoop/example/single_example/pocket --csv_file /root/KarmaLoop/example/single_example/single_example.csv
python -u generate_graph.py --protein_file_dir /root/KarmaLoop/example/single_example/raw --pocket_file_dir /root/KarmaLoop/example/single_example/pocket --graph_file_dir /root/KarmaLoop/example/single_example/graph
python -u loop_generating.py --graph_file_dir /root/KarmaLoop/example/single_example/graph --out_dir /root/KarmaLoop/example/single_example/test_result --batch_size 64 --random_seed 2023 --multi_conformation --scoring --save_file
```

```shell
(karmaloop) root ~# git clone https://github.com/karma211225/KarmaLoop.git
Cloning into 'KarmaLoop'...
remote: Enumerating objects: 226, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 226 (delta 7), reused 19 (delta 5), pack-reused 205 (from 1)
Receiving objects: 100% (226/226), 51.01 MiB | 2.88 MiB/s, done.
Resolving deltas: 100% (11/11), done.
(karmaloop) root ~# cd /root/KarmaLoop
(karmaloop) root KarmaLoop# cd /root/KarmaLoop/utils 
(karmaloop) root utils# python -u pre_processing.py --protein_file_dir /root/KarmaLoop/example/single_example/raw --pocket_file_dir /root/KarmaLoop/example/single_example/pocket --csv_file /root/KarmaLoop/example/single_example/single_example.csv
/root/anaconda3/envs/karmaloop/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/root/anaconda3/envs/karmaloop/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
########### Start pocket extraction ###########
pdb_ids: 3
(karmaloop) root utils# cd /root/KarmaLoop/utils 
(karmaloop) root utils# python -u generate_graph.py --protein_file_dir /root/KarmaLoop/example/single_example/raw --pocket_file_dir /root/KarmaLoop/example/single_example/pocket --graph_file_dir /root/KarmaLoop/example/single_example/graph 
/root/anaconda3/envs/karmaloop/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
########### Start generating graph ###########
pdb_ids: 3
### generating graph
(karmaloop) root utils# cd /root/KarmaLoop/utils 
(karmaloop) root utils# python -u loop_generating.py --graph_file_dir /root/KarmaLoop/example/single_example/graph --out_dir /root/KarmaLoop/example/single_example/test_result --batch_size 64 --random_seed 2023 --multi_conformation --scoring --save_file 
/root/anaconda3/envs/karmaloop/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/root/anaconda3/envs/karmaloop/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
########### Start modelling loop ###########
pdb_ids: 3
# load model
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.21it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.42it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.36it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.47it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.37it/s]
Total Time: 0.024430712591856717 min
Sample Num: 3
Multi Conformation Num: 5
# prediction
Time Spend: 0.0029638553969562054 ± 0.0049211410805583 min
Mean RMSD: 0.44922199845314026 ± 0.06493956595659256   
Medium RMSD: 0.4435935616493225 ± 0.053149569779634476
Max RMSD: 0.5131766200065613 ± 0.10040536522865295
Min RMSD: 0.3908957839012146 ± 0.04331246018409729
Success RATE(5A): 1.0 ± 0.0)
Success RATE(4.5A): 1.0 ± 0.0)
Success RATE(4A): 1.0 ± 0.0)
Success RATE(3.5A): 1.0 ± 0.0)
Success RATE(3A): 1.0 ± 0.0)
Success RATE(2.5A): 1.0 ± 0.0)
Success RATE(2A): 1.0 ± 0.0)
Success RATE(1A): 1.0 ± 0.0
# multi pose
Success RATE(5A): 1.0 
Success RATE(4.5A): 1.0
Success RATE(4A): 1.0
Success RATE(3.5A): 1.0
Success RATE(3A): 1.0
Success RATE(2.5A): 1.0
Success RATE(2A): 1.0
Success RATE(1A):  1.0
```
